services:
  # Node.js アプリケーション
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # デバッグポート
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/secure-chat.db
      - JWT_SECRET=dev-secret-key-change-in-production
    depends_on:
      db-setup:
        condition: service_completed_successfully
    # nodemonの代わりにnodeを直接使用
    command: node --inspect=0.0.0.0:9229 server.js
    restart: unless-stopped

  # データベース初期化用
  db-setup:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./data:/app/data
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./data/secure-chat.db
    command: npm run db:setup

volumes:
  node_modules: